
export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premiun Bank',
    headline: 'unlim transactions',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit enim exercitationem',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
}
export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlim Bank',
    headline: 'unlim transactions',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit enim exercitationem',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
}
export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Unlim Bank',
    headline: 'unlim transactions',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit enim exercitationem',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/svg-3.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
}